swagger: '2.0'
host: localhost:8080
basePath: /api

schemes:
- https

info:
  description: This is a Resume API
  version: 1.0.0
  title: Simple Resume API

  contact:
    email: marcusljx@grab.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: admins
  description: Secured Admin-only calls
- name: dev
  description: Operations available to regular developers
- name: public
  description: Operations available to public (exposed API calls)

paths:
  /uploadResumeDetails:
    post:
      tags:
      - admins
      summary: adds a resume
      operationId: addResume
      description: Adds a resume to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: ResumeObject
        description: Resume to add
        schema:
          $ref: '#/definitions/ResumeObject'
      responses:
        201:
          description: Resume successfully added
          schema:
            $ref: '#/definitions/ResumeAdded'
        400:
          description: invalid input, object invalid

  /getResume/{resumeID}:
    parameters:
      - name: resumeID
        in: path
        required: true
        description: ID of resume to obtain
        type: string
        format: uuid
        # example: d290f1ee-6c54-4b01-90e6-d701748f0851

    get:
      tags:
      - public
      summary: Returns resume
      operationId: getResume
      description: Returns a resume based on ID.
      produces:
      - application/json
      responses:
        200:
          description: Return resume
          schema:
            $ref: '#/definitions/ResumeObject'
        400:
          description: ID not found

definitions:
  ResumeObject:
    type: object
    required:
    - name
    - currentJob
    - previousJobs
    properties:
      name:
        type: string
        description: Name of Candidate

      currentJob:
        $ref: '#/definitions/Job'

      previousJobs:
        type: array
        items:
          $ref: '#/definitions/Job'

  Job:
    type: object
    required:
    - title
    - company
    properties:
      title:
        type: string
        description: Title of job
        example: Software Engineer in Test

      description:
        type: string
        description: Description about the job scope, responsibilities, etc.
        example: Development of Test Automation routines and infrastructure.

      company:
        type: string
        description: Name of Company
        example: Acronis Asia Research and Development

  ResumeAdded:
    properties:
      resumeID:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
